### ISSUE TITLE
Foot limit switch

### ISSUE THREAD

**Issue by JuanBarron2001** [JuanBarron2001/tester#2]
Need Help
add a limit switch for the foot

**Comment by chadr03** [comment]
I think this is closed.  At least it was working when we put the robot in the bag it would be a good idea to test at comp.  Just move the foot to the middle of its range and try to use the manual foot which is the left y joystick on the gamepad.  Use a stick or something to push the limit switch and the foot should stop.

**Comment by chadr03** [comment]
This appeared to be closed at comp
