### ISSUE TITLE
teleop in auto

### ISSUE THREAD

**Issue by JuanBarron2001** [JuanBarron2001/tester#8]
I made a commit to the code, would it be possible to test with Steamworks using the driver station in practice mode.

**Comment by chadr03** [comment]
I can check when I get home.  Steamworks has Sparks not talons so it won't work perfectly, but will crash if something is way off.  I can tell by looking at it that you need to change at least one thing.

Currently you put both teleopInit() and teleopPeriodic() into autonomousInit()

From what I have been told you should put teleopInit() into autonomousInit() then put teleopPeriodic() into autonomousPeriodic()

**Comment by chadr03** [comment]
I am not getting any major errors with when I load this, but I still think it needs to be as I stated before.

**Comment by JuanBarron2001** [comment]
I think it should be in the initialize because when it calls teleop mode it is going to end autonomous mode and jump into teleop.

**Comment by chadr03** [comment]
https://www.chiefdelphi.com/t/running-teleopperiodic-during-sandstorm/348765

https://www.chiefdelphi.com/t/teleop-in-sandstorm/348631

**Comment by chadr03** [comment]
seems to work whatever was done so I'm closing this
