### ISSUE TITLE
Change Blinkin Light on foot limit switch

### ISSUE THREAD

**Issue by chadr03** [JuanBarron2001/tester#9]
I think it would be beneficial for the blinkin lights to change once the foot limit switch is hit.  The drivers would know if the foot is all the way up without looking away from the robot.

**Comment by JuanBarron2001** [comment]
Is there a limit switch on the code or do I need to add one? And if so do you know what port is in?

**Comment by chadr03** [comment]
isReverseLimit() in the foot Subsystem
